# Generated by Django 3.1.5 on 2021-03-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bac_Mention',
            fields=[
                ('Mention', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('CodeDept', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomDep', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomeBacPlus2',
            fields=[
                ('CodeDiplome', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomDiplomeBacPlus2', models.CharField(max_length=60)),
                ('NatureDiplome', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='EtablissementDipBacPlus2',
            fields=[
                ('codeEtablissement', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('EtablissementDipBacPlus2', models.CharField(max_length=60)),
                ('Ville', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LPs',
            fields=[
                ('CodeLP', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomLP', models.CharField(max_length=60)),
                ('CodeDept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Lycee_Academie',
            fields=[
                ('CodeLycee', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomLycee', models.CharField(max_length=60)),
                ('Academie', models.CharField(max_length=60)),
                ('Ville', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableLPs',
            fields=[
                ('CodeResponsable', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomResponsable', models.CharField(max_length=100)),
                ('PrenomResponsable', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Specialites_DiplomeBacPlus2',
            fields=[
                ('spécialite_Option', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypesBac',
            fields=[
                ('CodeBac', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomBac', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('Nom_Ville', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LPs_DiplomeBacPlus2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeDiplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.diplomebacplus2')),
                ('CodeLP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lps')),
            ],
        ),
        migrations.CreateModel(
            name='LPs_Bac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeBac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typesbac')),
                ('CodeLP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lps')),
            ],
        ),
        migrations.AddField(
            model_name='lps',
            name='CodeResponsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.responsablelps'),
        ),
        migrations.CreateModel(
            name='Candidats',
            fields=[
                ('CIN_OU_Passport', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DateNaissance', models.CharField(max_length=100)),
                ('Nationalite', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Telephone1', models.CharField(max_length=12)),
                ('Telephone2', models.CharField(max_length=12)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Annee_Obtention_Bac', models.CharField(max_length=4)),
                ('MentionBac', models.CharField(max_length=100)),
                ('Academie', models.CharField(max_length=100)),
                ('Annee_Obtention_DiplomeBacPlus2', models.CharField(max_length=100)),
                ('DureeObtentionDiplomeBacPlus2', models.CharField(max_length=100)),
                ('Specialite_Diplome', models.CharField(max_length=100)),
                ('Dominance_Diplome', models.CharField(max_length=100)),
                ('EtablissementDipBacPlus2', models.CharField(max_length=100)),
                ('Ville_DiplomeBacPlus2', models.CharField(max_length=100)),
                ('Annee_Obtention_1ereAnnee', models.CharField(max_length=100)),
                ('Note_1ere_Annee_Diplome', models.FloatField(max_length=10)),
                ('Note_2eme_Annee_Diplome', models.FloatField(max_length=10)),
                ('Note_Obtention_Diplome', models.CharField(max_length=100)),
                ('Note_Semestre1', models.FloatField(max_length=10)),
                ('Note_Semestre2', models.FloatField(max_length=10)),
                ('Note_Semestre3', models.FloatField(max_length=10)),
                ('Note_Semestre4', models.FloatField(max_length=10)),
                ('CodeLPChoisie', models.CharField(max_length=100)),
                ('CNE_OU_Massar', models.CharField(max_length=100)),
                ('CodeBac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typesbac')),
                ('CodeDiplomeBacPlus2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.diplomebacplus2')),
                ('Lycee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lycee_academie')),
            ],
        ),
    ]
