# Generated by Django 3.1.7 on 2021-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='Annee_Obtention_1ereAnnee',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Obtention_Diplome',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='diplomebacplus2',
            name='NatureDiplome',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
