# Generated by Django 3.1.7 on 2021-03-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210303_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesbac',
            name='NomBac',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
