# Generated by Django 3.1.5 on 2021-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesBac2',
            fields=[
                ('CodeBac', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('NomBac', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
