# Generated by Django 3.1.7 on 2021-03-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_typesbac2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='Note_1ere_Annee_Diplome',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_2eme_Annee_Diplome',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Obtention_Diplome',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Semestre1',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Semestre2',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Semestre3',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Note_Semestre4',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
