# Generated by Django 3.1.7 on 2021-03-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210308_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='CodeBac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.typesbac'),
        ),
    ]
