# Generated by Django 3.1.7 on 2021-03-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210308_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidats',
            name='Academie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Annee_Obtention_1ereAnnee',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Annee_Obtention_Bac',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Annee_Obtention_DiplomeBacPlus2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='CNE_OU_Massar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='CodeLPChoisie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Dominance_Diplome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='DureeObtentionDiplomeBacPlus2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='EtablissementDipBacPlus2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Lycee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.lycee_academie'),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='MentionBac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Specialite_Diplome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidats',
            name='Ville_DiplomeBacPlus2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
